# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250316-020046-crunchy-monitor

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  # - name: "FallbackClassifier"
  #   threshold: 0.4  # If confidence is below 40%, trigger fallback response
  #   ambiguity_threshold: 0.1
    
  # 1️⃣ Use SpaCy NLP to improve sentence understanding
  - name: "SpacyNLP"
    model: "en_core_web_md"  # Make sure this model is installed!
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"

  # 2️⃣ Use DIETClassifier for intent classification & ranking
  - name: "DIETClassifier"
    epochs: 100  # More training makes the bot smarter
    ranking_length: 3  # Show the top 3 matching intents if unsure

  # 3️⃣ Enable Fuzzy Matching for typos & close matches (corrects spelling mistakes )
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
 

  # 4️⃣ Use a Response Selector for FAQ-style questions(finds the best matching answer from its FAQ)
  - name: "ResponseSelector"
    epochs: 100

  # 5️⃣ Use a basic text classifier as backup(chatbot is unsure, it asks for clarification instead of guessing)
  - name: "FallbackClassifier"
    threshold: 0.6
    ambiguity_threshold: 0.1


policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "utter_fallback"
    enable_fallback_prediction: True
