# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250316-020046-crunchy-monitor

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  # 1️⃣ Use SpaCy NLP to improve sentence understanding
  - name: "SpacyNLP"
    model: "en_core_web_md"  # Make sure this model is installed!
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"

  # 2️⃣ Use DIETClassifier for intent classification & ranking
  - name: "DIETClassifier"
    epochs: 100  # More training makes the bot smarter
    ranking_length: 3  # Show the top 3 matching intents if unsure

  # 3️⃣ Enable Fuzzy Matching for typos & close matches (corrects spelling mistakes )
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "FallbackClassifier"
    threshold: 0.6  # If intent confidence is low, fallback to a default response
    ambiguity_threshold: 0.1  # Handle similar intents better

  # 4️⃣ Use a Response Selector for FAQ-style questions(finds the best matching answer from its FAQ)
  - name: "ResponseSelector"
    epochs: 100

  # 5️⃣ Use a basic text classifier as backup(chatbot is unsure, it asks for clarification instead of guessing)
  - name: "FallbackClassifier"
    threshold: 0.5
    ambiguity_threshold: 0.1

# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies: null
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
